steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Connecting to GCP VM and deploying app..."

        gcloud compute ssh g499_bt19@instance-20250615-042814 \
          --zone "us-central1-f" \
          --project "blissful-mile-461403-i2"   \
          --command="
            set -e

            deploy() {
              echo '[DEPLOY] Attempting normal deployment...'
              cd /home/g499_bt19/artatlas_backend || return 1

              echo '[DEPLOY] Resetting Git to clean state...'
              git reset --hard HEAD || return 1
              git clean -fd || return 1
              git pull || return 1

              docker compose down --remove-orphans || true
              docker compose up -d --build || return 1

              echo '[DEPLOY] Initial deployment successful.'
              return 0
            }

            reset_and_redeploy() {
              echo '[RESET] Starting fallback deployment...'
              cd /home/g499_bt19 || return 1

              echo '[RESET] Removing old project...'
              sudo rm -rf artatlas_backend

              echo '[RESET] Cloning fresh repo...'
              git clone https://github.com/vijayshankarrealdeal/artatlas_backend.git || return 1
              cd artatlas_backend || return 1

              echo '[RESET] Validating folder structure...'
              find . -maxdepth 2
              if [ ! -d 'frontend' ] || [ ! -d 'backend' ] || [ ! -f 'docker-compose.yml' ]; then
                echo '[ERROR] Missing expected folder structure. Aborting.'
                exit 1
              fi

              echo '[RESET] Cleaning Docker (images, networks)...'
              docker compose down --remove-orphans || true
              docker image prune -af || true
              docker builder prune -af || true
              docker network prune -f || true

              echo '[RESET] Rebuilding containers...'
              docker compose up -d --build || return 1

              echo '[RESET] Fallback deployment completed successfully.'
              return 0
            }

            if ! deploy; then
              echo '[WARN] Initial deployment failed. Triggering fallback...'
              reset_and_redeploy
            fi
          "

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
