steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Connecting to GCP VM and deploying app..."

        gcloud compute ssh g499_bt19@instance-20250614-071658 \
          --zone "us-central1-f" \
          --project "blissful-mile-461403-i2" \
          --command="
            set -e

            deploy() {
              echo 'Attempting normal deployment...'
              cd /home/g499_bt19/artatlas_backend || exit 1
              git pull || exit 1
              docker compose down --remove-orphans || true
              docker compose up -d --build || return 1
              return 0
            }

            reset_and_redeploy() {
              echo 'Build failed. Resetting and starting fresh...'
              rm -rf /home/g499_bt19/artatlas_backend
              git clone https://github.com/vijayshankarrealdeal/artatlas_backend.git /home/g499_bt19/artatlas_backend || exit 1
              cd /home/g499_bt19/artatlas_backend || exit 1
              docker system prune -af --volumes || true
              docker compose up -d --build || exit 1
              echo 'Recovery deployment completed.'
            }

            if ! deploy; then
              reset_and_redeploy
            else
              echo 'Initial deployment successful.'
            fi
          "

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
