steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Connecting to GCP VM and deploying app..."
        gcloud compute ssh --zone "us-central1-f" "instance-20250614-071658" --project "blissful-mile-461403-i2"
# Optional timeout
timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY

