version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - artatlas-net
    volumes:
      - .:/app  # optional: only needed during dev

  db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - artatlas-net
    environment:
      - GOOGLE_CLOUD_PROJECT=blissful-mile-461403-i2

volumes:
  mongodb-data:

networks:
  artatlas-net:
