version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/app:cached
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    networks:
      - artatlas-net

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    networks:
      - artatlas-net

volumes:
  mongodb-data:

networks:
  artatlas-net:
